import { Product } from './types';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Helado de Vainilla Clásica',
    category: 'helado',
    price: 4.99,
    description: 'Cremoso helado de vainilla hecho con vainilla real de Madagascar. Una experiencia clásica y elegante.',
    image: '🍦',
    imageUrl: undefined,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Helado de Chocolate Belga',
    category: 'helado',
    price: 5.49,
    description: 'Rico helado de chocolate hecho con cacao belga premium. Intenso y delicioso.',
    image: '🍫',
    imageUrl: undefined,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Helado de Fresa Natural',
    category: 'helado',
    price: 4.99,
    description: 'Refrescante helado hecho con fresas frescas de temporada. Dulce y natural.',
    image: '🍓',
    imageUrl: undefined,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Helado de Menta con Chips',
    category: 'helado',
    price: 5.49,
    description: 'Helado de menta fresca con chips de chocolate. Refrescante y crujiente.',
    image: '🌿',
    imageUrl: undefined,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Helado de Caramelo Salado',
    category: 'helado',
    price: 5.99,
    description: 'Delicioso helado con remolinos de caramelo salado. El equilibrio perfecto entre dulce y salado.',
    image: '🍮',
    imageUrl: undefined,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Tarta de Queso Clásica',
    category: 'postre',
    price: 6.99,
    description: 'Cremosa tarta de queso con base de galleta graham. Suave, rica y absolutamente irresistible.',
    image: '🍰',
    imageUrl: undefined,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '7',
    name: 'Brownie de Chocolate',
    category: 'postre',
    price: 4.49,
    description: 'Brownie de chocolate denso y húmedo con nueces. Perfecto para los amantes del chocolate.',
    image: '🍫',
    imageUrl: undefined,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '8',
    name: 'Tiramisú Italiano',
    category: 'postre',
    price: 7.49,
    description: 'Auténtico tiramisú italiano con café espresso y mascarpone. Una experiencia italiana genuina.',
    image: '☕',
    imageUrl: undefined,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '9',
    name: 'Tarta de Limón',
    category: 'postre',
    price: 5.99,
    description: 'Tarta de limón ácida con merengue esponjoso. Refrescante y perfectamente balanceada.',
    image: '🍋',
    imageUrl: undefined,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '10',
    name: 'Pastel de Chocolate',
    category: 'postre',
    price: 8.99,
    description: 'Pastel de chocolate de tres capas con ganache. El sueño de todo amante del chocolate.',
    image: '🎂',
    imageUrl: undefined,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
